src/presentation/Blog.Web/Areas/Admin/Controllers/ArticleController.cs
using Blog.Application.Dto.ArticleDto;
using Blog.Application.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Blog.Web.Areas.Admin.Controllers;

[Area("Admin")]
[Authorize(Roles = "Administrator, Editör")]
public class ArticleController : BaseController
{
	private readonly IArticleService _articleService;

	public ArticleController(IArticleService articleService)
	{
		_articleService = articleService;
	}

	#region Functions
	#region Create
	[HttpPost]
	public async ValueTask<IActionResult> Insert(ArticleInsertDto data)
	{
		var result = await _articleService.InsertAsync(data, ModelState);

		if (true.Equals(result.Success))
			return Ok(result);

		return new ObjectResult(result.Value != null ? result.Value : result)
		{
			StatusCode = 400
		};
	}
	#endregion

	#region Read
	public IActionResult Index()
	{
		return View();
	}

	public IActionResult Insert()
	{
		return View();
	}

	public IActionResult Series()
	{
		return View();
	}
	#endregion

	#region Update

	#endregion

	#region Delete

	#endregion
	#endregion
}

src/presentation/Blog.Web/Areas/Admin/Views/Article/Index.cshtml
@{
	ViewBag.Title = "Makale Yönetimi";
	Layout = "~/Areas/Admin/Views/Shared/_MainLayout.cshtml";
}

<div class="breadcrumbs">
	<h4>Makale Yönetimi</h4>
	<ul>
		<li><a asp-route="AdminHome">Anasayfa</a></li>
		<li>
			<i class="fa-duotone fa-angle-right fa-fw fc-blue"></i>
		</li>
		<li>Makale Yönetimi</li>
	</ul>
</div>

<div class="wrapper">
	<div class="grid">
		<div class="col-12">
			<div class="card">
				<div class="card-header pd-x">
					<h4>Makaleler</h4>
					<div class="dropdown">
						<a href="javascript:void(0)" data-dropdown="#card-menu">
							<i class="fa-duotone fa-bars fa-fw fs-15 fc-blue"></i>
						</a>
						<div class="drop-down" id="card-menu">
							<ul>
								<li><a asp-route="AdminArticleInsert"><i class="fa-duotone fa-plus fa-fw"></i>&nbsp;Makale Ekle</a></li>
							</ul>
							<ul>
								<li><a asp-route="AdminArticleSeries"><i class="fa-duotone fa-books fa-fw"></i>&nbsp;Seri Makaleler</a></li>
							</ul>
							<ul>
								<li><a asp-route="AdminBibliographies"><i class="fa-duotone fa-bookmark fa-fw"></i>&nbsp;Kaynakça</a></li>
							</ul>
						</div>
					</div>
				</div>
				<div class="card-body pd">

					<!--Makale listesi-->

					<table class="border-btm">
						<thead>
							<tr>
								<th>
									<input type="checkbox" />
								</th>
								<th>Başlık</th>
								<th>Ekleyen</th>
								<th>Kategori</th>
								<th class="text-center">Eklenme</th>
								<th class="text-center">Okunma</th>
								<th class="text-center">Yorum</th>
								<th class="text-center">Durum</th>
								<th class="text-center">İşlem</th>
							</tr>
						</thead>
						<tbody>
							@for (int i = 1; i <= 20; i++)
							{
								<tr>
									<td><input type="checkbox" /></td>
									<td>Buraya makale başlığı gelecek</td>
									<td>
										<a href="#">Çağlar ÖZCAN</a>
									</td>
									<td>
										<a href="#">kategori1</a>,
										<a href="#">kategori2</a>,
										<a href="#">kategori3</a>
									</td>
									<td class="text-center">10 Ekim 2021 23:36</td>
									<td class="text-center font-numeric">100</td>
									<td class="text-center font-numeric">15</td>
									<td class="text-center">
										<span class="status-success">Yayında</span>
									</td>
									<td class="text-center">
										<div class="dropdown">
											<a href="javascript:void(0)" data-dropdown="#tbl-menu@(Html.Raw(i))">
												<i class="cdi cdi-ellipsis"></i>
											</a>

											<div class="drop-down" id="tbl-menu@(Html.Raw(i))">
												<ul>
													<li><a href="#"><i class="cdi cdi-admin-post"></i>&nbsp;&nbsp;Sabitle</a></li>
													<li><a href="#"><i class="cdi cdi-remove"></i>&nbsp;&nbsp;Engelle</a></li>
													<li><a href="#"><i class="cdi cdi-edit"></i>&nbsp;&nbsp;Güncelle</a></li>
													<li><a href="#"><i class="cdi cdi-menu-alt"></i>&nbsp;&nbsp;Detaylar</a></li>
													<li class="seperator"></li>
													<li><a href="#"><i class="cdi cdi-trash"></i>&nbsp;&nbsp;Sil</a></li>
												</ul>
											</div>
										</div>
									</td>
								</tr>
							}

						</tbody>
					</table>

					<ul class="pagination pg-direction-right">
						<li class="arrow">
							<a href="#">
								<i class="cdi cdi-arrow-left-alt2"></i>
							</a>
						</li>
						<li>
							<a href="#">1</a>
						</li>
						<li>
							<a href="#">2</a>
						</li>
						<li>
							<a href="#">3</a>
						</li>
						<li class="active">
							<a href="#">4</a>
						</li>
						<li>
							<a href="#">5</a>
						</li>
						<li>
							<a href="#">6</a>
						</li>
						<li>
							<a href="#">7</a>
						</li>
						<li class="arrow">
							<a href="#">
								<i class="cdi cdi-arrow-right-alt2"></i>
							</a>
						</li>
					</ul>

					<!--Makale listesi-->

				</div>
			</div>
		</div>
	</div>
</div>

src/presentation/Blog.Web/Areas/Admin/Views/Article/Insert.cshtml
@{
	ViewBag.Title = "Makale Ekle";
	Layout = "~/Areas/Admin/Views/Shared/_ArticleInsertLayout.cshtml";
}

<div class="breadcrumbs">
	<h4>Makale Ekle</h4>
	<ul>
		<li><a asp-route="AdminHome">Anasayfa</a></li>
		<li>
			<i class="fa-duotone fa-angle-right fa-fw"></i>
		</li>
		<li><a asp-route="AdminArticle">Makale Yönetimi</a></li>
		<li>
			<i class="fa-duotone fa-angle-right fa-fw"></i>
		</li>
		<li>Makale Ekle</li>
	</ul>
</div>

<div class="modal" id="photoSelect">
	<div class="modal-container modal-xlg">
		<div class="modal-title">
			<div class="title">Öne Çıkan Görsel</div>
			<a href="javascript:void(0)" class="close" data-dismiss="modal">
				<i class="fa-duotone fa-xmark fa-fw fc-blue"></i>
			</a>
		</div>
		<div class="modal-content" id="image-galley-content">
			<div class="gallery" data-columns="10" id="main-gallery"></div>
		</div>
		<div class="modal-footer footer-align-right">
			<button class="btn btn-blue" data-close="modal">Kapat</button>
		</div>
	</div>
</div>

<div class="modal" id="fileSelect">
	<div class="modal-container modal-xlg">
		<div class="modal-title">
			<div class="title">Dosya Ekle</div>
			<a href="javascript:void(0)" class="close" data-dismiss="modal">
				<i class="fa-duotone fa-xmark fa-fw fc-blue"></i>
			</a>
		</div>
		<div class="modal-content" id="file-galley-content">
			<div class="gallery" data-columns="10" id="file-main-gallery"></div>
		</div>
		<div class="modal-footer footer-align-right">
			<button class="btn btn-blue" data-close="modal">Kapat</button>
		</div>
	</div>
</div>

<div class="wrapper">
	<form id="article-insert-form" asp-area="Admin" asp-controller="Article" asp-action="Insert">
		<div class="grid">
			<div class="col-9">
				<div class="tab tab-bg soft-border" data-tab="tab">
					<!--Tab Menü-->
					<div class="tab-menu-fixed">
						<div class="tab-menu-item active">
							<a href="javascript:void(0)" data-tab-target="#general-setting">
								<i class="fa-duotone fa-book-open-cover fa-fw fc-blue"></i>
								&nbsp;
								Makale Metni
							</a>
						</div>
						<div class="tab-menu-item">
							<a href="javascript:void(0)" data-tab-target="#article-setting">
								<i class="fa-duotone fa-code-simple fa-fw fc-blue"></i>
								&nbsp;
								Meta
							</a>
						</div>
						<div class="tab-menu-item">
							<a href="javascript:void(0)" data-tab-target="#image-setting">
								<i class="fa-duotone fa-code-fork fa-fw fc-blue"></i>
								&nbsp;
								Kategori & Etiket
							</a>
						</div>
						<div class="tab-menu-item">
							<a href="javascript:void(0)" data-tab-target="#mail-setting">
								<i class="fa-duotone fa-file-pen fa-fw fc-blue"></i>
								&nbsp;
								Dosya
							</a>
						</div>
						<div class="tab-menu-item">
							<a href="javascript:void(0)" data-tab-target="#comment-setting">
								<i class="fa-duotone fa-bookmark fa-fw fc-blue"></i>
								&nbsp;
								Kaynakça
							</a>
						</div>
					</div>
					<!--Tab Menü-->
					<!--Tab İçerik-->
					<div class="tab-content">
						<!--Genel Ayarlar içeriği-->
						<div class="tab-item show" id="general-setting">
							<div class="form-group">
								<input type="text" name="Title" class="input fc-l" placeholder="Makale Başlığı" />
								<span class="vld-Title"></span>
							</div>

							<div class="form-group">
								<div id="contentEditor" style="height:600px;"></div>
								<input type="hidden" name="Content" value="" />
								<span class="vld-Content"></span>
							</div>
						</div>
						<!--Genel Ayarlar içeriği-->
						<!--Makale Ayarları-->
						<div class="tab-item" id="article-setting">
							<div class="form-group">
								<label class="label"><strong>Makale Açıklama</strong></label>
								<textarea name="Description" class="input" style="height:150px;"></textarea>
								<span class="vld-Description"></span>
							</div>
							<div class="form-group">
								<label class="label"><strong>Makale Linki</strong></label>
								<input type="text" name="Slug" class="input" />
								<small>Boş bırakırsanız otomatik oluşturulacaktır.</small>
								<span class="vld-Slug"></span>
							</div>
						</div>
						<!--Makale Ayarlar-->
						<!--Resim Yükleme Ayarları-->
						<div class="tab-item" id="image-setting">
							<div class="grid">
								<div class="col-6" style="padding-bottom:20px;">
									<div class="form-group">
										<label class="label"><strong>Makale Kategorileri</strong></label>
									</div>
									@await Component.InvokeAsync("CategoryTreeComponent", null)
									<span class="vld-Categories"></span>
								</div>
								<div class="col-6">
									<div class="form-group">
										<label class="label"><strong>Makale Etiketleri</strong></label>
									</div>
									<div class="ticket-container" id="ticket-container">
										<div class="ticket">
											<span>sql</span>
											<a href="javascript:void(0)">
												<i class="fa-duotone fa-xmark"></i>
											</a>
										</div>
									</div>
									<div class="input-group">
										<input type="text" name="ticketText" class="input" placeholder="Etiket ismi..." />
										<button class="btn btn-primary group-text">
											<i class="fa-duotone fa-plus-large fa-fw fc-white"></i>
										</button>
									</div>
									<input type="hidden" name="Tickets" value="" />
									<span class="vld-Tickets"></span>
								</div>
							</div>

						</div>
						<!--Resim Yükleme Ayarları-->
						<!--Dosya Ekle-->
						<div class="tab-item" id="mail-setting">
							<div class="file-box" id="article-files"></div>
							<div class="hr mt-2 mb-2"></div>
							<button class="btn btn-primary mb-1" data-modal="#fileSelect">Dosya Ekle</button>
						</div>
						<!--Dosya Ekle-->
						<!--Yorum Ayarları-->
						<div class="tab-item" id="comment-setting">
							<table id="source-list">
								<thead>
									<tr>
										<th style="width:30px;">#</th>
										<th>İsim</th>
										<th>Bağlantı</th>
										<th style="width:30px;">&nbsp;</th>
									</tr>
								</thead><tbody>
								</tbody>
							</table>

							<div class="hr mt-2 mb-2"></div>

							<div class="form-group">
								<label class="label">İsim</label>
								<input type="text" name="sourceTitle" class="input" id="sourceTitle" placeholder="Kaynakça Adı"/>
								<span class="vld-Title"></span>
							</div>
							<div class="form-group">
								<label class="label">Bağlantı</label>
								<input type="text" name="sourceTitle" class="input" id="sourceLink" placeholder="Kaynakça Bağlantısı" />
								<span class="vld-Title"></span>
							</div>

							<div class="form-group text-right">
								<button class="btn btn-primary group-text" id="btnAddSource">
									<i class="fa-duotone fa-plus-large fa-fw fc-white"></i> Ekle
								</button>
							</div>
						</div>
						<!--Yorum Ayarları-->
					</div>
					<!--Tab İçerik-->
				</div>
			</div>
			<div class="col-3">
				<div class="card">
					<div class="card-body pd">
						<div class="flex flex-sb">
							<select name="SaveType" id="save-type" class="chselect">
								<option value="1" selected>Kaydet ve Yayınla</option>
								<option value="2">Taslak Olarak Kaydet</option>
								<option value="3">PDF Olarak Kaydet</option>
							</select>
							<div class="flex-seperator"></div>
							<button class="btn btn-primary" id="btn-article-insert" type="submit">Kaydet</button>
						</div>
					</div>
				</div>

				<div class="card">
					<div class="card-body pd text-center">
						<img class="article-cover-image" id="articleCover" style="display:none;" />
						<a href="javascript:void(0)" data-modal="#photoSelect">Öne çıkan görsel seç</a>
						<input type="hidden" name="CoverPhotoId" id="CoverPhotoId" value="" />
					</div>
				</div>
			</div>
		</div>
	</form>
</div>

<script>
	var editor1cfg = {}
	editor1cfg.toolbar = "mytoolbar";
	editor1cfg.toolbar_mytoolbar = "{paragraphs,bold,italic,underline,strike}|{forecolor,backcolor,ucase,lcase}|{justifyleft,justifycenter,justifyright,justifyfull,indent,outdent}|{insertorderedlist,insertunorderedlist,superscript,subscript}|{insertlink,inserttable,insertimage,insertblockquote,insertvideo,insertcode,code,insertchars}#{undo,redo,preview,html2pdf,fullscreenenter,fullscreenexit}";
	editor1cfg.skin = 'rounded-corner';
	var editor1 = new RichTextEditor("#contentEditor", editor1cfg);

	function deleteFileItem(e) {
		e = e || window.event;
		var targ = e.target || e.srcElement || e;
		targ.parentNode.parentNode.remove();
	}

	window.addEventListener('DOMContentLoaded', (event) => {
		FormValidation.init({
			formSelector: '#article-insert-form',
			sendAjax: true,
			ajaxAfter: function () {
				dtCategory.renderBody();
			},
			inputs: [
				{
					name: 'Title',
					rules: [
						{ rule: 'required', message: 'Makale başlığı alanı zorunludur.' }
					],
				},
				{
					name: 'Content',
					rules: [
						{ rule: 'required', message: 'Makale içeriği alanı zorunludur.' }
					],
				},
				{
					name: 'Description',
					rules: [
						{ rule: 'required', message: 'Kısa makale açıklaması zorunludur.' }
					],
				},
				{
					name: 'Tickets',
					rules: [
						{ rule: 'required', message: 'Makale için en az bir etiket belirlemelisiniz.' }
					],
				}
			]
		});

		var gallery = new PhotoSelector({
			selector: '#main-gallery', perData: 32, searchValue: 'jpg,png,jpeg,gif,svg', eh: function (id, path, name) {
				document.getElementById('CoverPhotoId').value = id;
				var prvImg = document.getElementById('articleCover');
				prvImg.src = path;
				prvImg.style.display = 'block';
			}
		});

		const galleryContent = document.getElementById('image-galley-content');
		const mainGallery = document.getElementById('main-gallery');
		let idealColumnSize = galleryContent.clientWidth < 640 ? 135 : 150;
		window.addEventListener('resize', (e) => {
			let columnSize = Math.min(Math.round(galleryContent.clientWidth / idealColumnSize), 10) || 1;
			mainGallery.setAttribute('data-columns', columnSize);
		});


		var fGallery = new PhotoSelector({
			selector: '#file-main-gallery', perData: 32, searchValue: 'pdf,zip,rar,xls,txt,json,xml', eh: function (id, path, name) {
				let fileItem = '<div class="file-delete-button">\
															<a href="javascript:void(0)" onclick="deleteFileItem(this)">\
																<i class="fa-duotone fa-xmark fa-fw"></i>\
															</a>\
														</div>\
														<div class="file-icon">\
															<i class="fa-duotone fa-file-lines fa-fw"></i>\
															<input type="hidden" name="Attachments[]" value="' + id + '">\
														</div>\
															<div class="file-name">'+ name + '</div>';

				let fileDiv = document.createElement('div');
				fileDiv.className = 'file-item';
				fileDiv.innerHTML = fileItem;

				const fileBox = document.getElementById('article-files');
				fileBox.appendChild(fileDiv);
			}
		});
		const fileGalleryContent = document.getElementById('file-galley-content');
		const fileGallery = document.getElementById('file-main-gallery');
		idealColumnSize = fileGalleryContent.clientWidth < 640 ? 135 : 150;
		window.addEventListener('resize', (e) => {
			let columnSize = Math.min(Math.round(fileGalleryContent.clientWidth / idealColumnSize), 10) || 1;
			fileGallery.setAttribute('data-columns', columnSize);
		});



		//Kaynak ekleme

		const sourceButton = document.getElementById('btnAddSource');
		const sourceTitle = document.getElementById('sourceTitle');
		const sourceLink = document.getElementById('sourceLink');
		const sourceList = document.querySelector('#source-list tbody');
		let sourceNum = 1;
		sourceButton.addEventListener('click', (e) => {
			let tr = document.createElement('TR');
			
			let numberTd = document.createElement('TD');
			numberTd.innerHTML = sourceNum;

			let titleTd = document.createElement('TD');
			titleTd.innerHTML = sourceTitle.value;

			let linkTd = document.createElement('TD');
			linkTd.innerHTML = sourceLink.value;

			let buttonTd = document.createElement('TD');
			let deleteButton = document.createElement('A');
			deleteButton.setAttribute('href', "javascript:void(0)");
			deleteButton.addEventListener('click', (e) => { 
				e.target.parentNode.parentNode.parentNode.remove();
				console.log(sourceList.childNodes);
			});
			deleteButton.innerHTML = '<i class="fa-duotone fa-trash-can fa-fw fc-red"></i>';
			buttonTd.appendChild(deleteButton);

			tr.appendChild(numberTd);
			tr.appendChild(titleTd);
			tr.appendChild(linkTd);
			tr.appendChild(buttonTd);
			sourceList.appendChild(tr);

			sourceNum++;
		});
	});
</script>

src/presentation/Blog.Web/Areas/Admin/Views/Article/Series.cshtml
@{
	ViewBag.Title = "Seri Makaleler";
	Layout = "~/Areas/Admin/Views/Shared/_MainLayout.cshtml";
}

<div class="breadcrumbs">
	<h4>Seri Makaleler</h4>
	<ul>
		<li><a asp-route="AdminHome">Anasayfa</a></li>
		<li>
			<i class="fa-duotone fa-angle-right fa-fw fc-blue"></i>
		</li>
		<li><a asp-route="AdminArticle">Makale Yönetimi</a></li>
		<li>
			<i class="fa-duotone fa-angle-right fa-fw fc-blue"></i>
		</li>
		<li>Seri Makaleler</li>
	</ul>
</div>

<div class="wrapper">
	<div class="grid">
		<div class="col-12">
			<div class="card">
				<div class="card-header pd-x">
					<h4>Seri Makaleler</h4>
					<div class="dropdown">
						<a href="javascript:void(0)" data-dropdown="#card-menu">
							<span class="svg-icon svg-icon-primary">
                                <!--begin::Svg Icon-->
                                <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
                                    <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                        <rect x="0" y="0" width="24" height="24" />
                                        <rect fill="#000000" x="4" y="5" width="16" height="3" rx="1.5" />
                                        <path d="M5.5,15 L18.5,15 C19.3284271,15 20,15.6715729 20,16.5 C20,17.3284271 19.3284271,18 18.5,18 L5.5,18 C4.67157288,18 4,17.3284271 4,16.5 C4,15.6715729 4.67157288,15 5.5,15 Z M5.5,10 L18.5,10 C19.3284271,10 20,10.6715729 20,11.5 C20,12.3284271 19.3284271,13 18.5,13 L5.5,13 C4.67157288,13 4,12.3284271 4,11.5 C4,10.6715729 4.67157288,10 5.5,10 Z" fill="#000000" opacity="0.3" />
                                    </g>
                                </svg><!--end::Svg Icon-->
                            </span>
						</a>
						<div class="drop-down" id="card-menu">
							<ul>
								<li><a asp-route="AdminArticleInsert"><i class="cdi cdi-plus-alt2"></i>&nbsp;&nbsp;Makale Ekle</a></li>
							</ul>
							<ul>
								<li><a asp-route="ArticleInsert"><i class="cdi cdi-list-view"></i>&nbsp;&nbsp;Seri Makaleler</a></li>
							</ul>
						</div>
					</div>
				</div>
				<div class="card-body pd">

					<!--Makale listesi-->

					<table class="border-btm">
						<thead>
							<tr>
								<th>
									<input type="checkbox" />
								</th>
								<th>Başlık</th>
								<th>Ekleyen</th>
								<th>Kategori</th>
								<th class="text-center">Eklenme</th>
								<th class="text-center">Okunma</th>
								<th class="text-center">Yorum</th>
								<th class="text-center">Durum</th>
								<th class="text-center">İşlem</th>
							</tr>
						</thead>
						<tbody>
							@for (int i = 1; i <= 20; i++)
							{
								<tr>
									<td><input type="checkbox" /></td>
									<td>Buraya makale başlığı gelecek</td>
									<td>
										<a href="#">Çağlar ÖZCAN</a>
									</td>
									<td>
										<a href="#">kategori1</a>,
										<a href="#">kategori2</a>,
										<a href="#">kategori3</a>
									</td>
									<td class="text-center">10 Ekim 2021 23:36</td>
									<td class="text-center font-numeric">100</td>
									<td class="text-center font-numeric">15</td>
									<td class="text-center">
										<span class="status-success">Yayında</span>
									</td>
									<td class="text-center">
										<div class="dropdown">
											<a href="javascript:void(0)" data-dropdown="#tbl-menu@(Html.Raw(i))">
												<i class="cdi cdi-ellipsis"></i>
											</a>

											<div class="drop-down" id="tbl-menu@(Html.Raw(i))">
												<ul>
													<li><a href="#"><i class="cdi cdi-admin-post"></i>&nbsp;&nbsp;Sabitle</a></li>
													<li><a href="#"><i class="cdi cdi-remove"></i>&nbsp;&nbsp;Engelle</a></li>
													<li><a href="#"><i class="cdi cdi-edit"></i>&nbsp;&nbsp;Güncelle</a></li>
													<li class="seperator"></li>
													<li><a href="#"><i class="cdi cdi-trash"></i>&nbsp;&nbsp;Sil</a></li>
												</ul>
											</div>
										</div>
									</td>
								</tr>
							}

						</tbody>
					</table>

					<ul class="pagination pg-direction-right">
						<li class="arrow">
							<a href="#">
								<i class="cdi cdi-arrow-left-alt2"></i>
							</a>
						</li>
						<li>
							<a href="#">1</a>
						</li>
						<li>
							<a href="#">2</a>
						</li>
						<li>
							<a href="#">3</a>
						</li>
						<li class="active">
							<a href="#">4</a>
						</li>
						<li>
							<a href="#">5</a>
						</li>
						<li>
							<a href="#">6</a>
						</li>
						<li>
							<a href="#">7</a>
						</li>
						<li class="arrow">
							<a href="#">
								<i class="cdi cdi-arrow-right-alt2"></i>
							</a>
						</li>
					</ul>

					<!--Makale listesi-->

				</div>
			</div>
		</div>
	</div>
</div>